import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-gray-400">
        <div className="flex flex-col">
          <h1 className="text-lg font-bold">Component built by ChatGPT</h1>
          <Link href="/login">Login (react-hook-form)</Link>
          <Link href="/register">Register (react-hook-form)</Link>
        </div>
      </main>
    </>
  );
}
